In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
ar_1 = np.arange(1,4)

In [38]:
def mean(a):
    c= 0
    d= 0
    for i in a:
        c= c + i #summation of all the numbers
        d= d + 1 # counter
    mean_number = c / d
    return mean_number

In [42]:
mean(ar_1)

2.5

In [67]:
def median(a):
    d= 0
    for i in a:
        d= d+1 # counter
    if d % 2 == 0:
        
        index = d //2 
        f1 = a[index-1] #index starts from zero
        f2 = a[index]
        mead = (f1+f2)/2
        return mead
    else:
        index = (d//2) + 1 #getting the index of the number
        return a[index-1]

In [71]:
median(ar_1)

4.5

In [69]:
ar_1 = np.arange(0,10)

In [70]:
ar_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
mean(ar_1)

1.5

In [86]:
def median(a):
    c = 0
    for i in a :
        c = c+1 # counter
    if c % 2 == 0:
        index = (c // 2)-1
        f1 = a[index]
        f2 = a[index+1]
        mean = (f1+f2)/2
        return mean
    else:
        index = (c // 2)
        return a[index]

In [87]:
ar_1 = np.arange(1,12)

In [88]:
ar_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
mean(ar_1)

6.0

In [90]:
median(ar_1)

6

In [91]:
ar_2 = np.random.randn(10)

In [92]:
ar_2

array([-1.78910741, -0.46104106,  0.78424973,  1.75061352,  0.66960268,
        0.78159895,  1.19640544,  0.99431449,  0.31390031, -0.83238815])

In [99]:
ar_3 = np.random.randint(50, 100, size = 10)

In [100]:
ar_3

array([60, 50, 77, 86, 67, 75, 73, 68, 91, 88])

In [101]:
mean(ar_3)

73.5

In [102]:
mean(ar_2)

0.34081484928958189

In [103]:
median(ar_3)

71.0

In [142]:
arr_4 = np.array([1,2,3,4,4,4,5,3])
print(arr_4)

[1 2 3 4 4 4 5 3]


In [140]:
def mode(a):
    c = 0
    c2 = 0
    for i in a:
        for j in a:
            if  i == j:
                c = c+1
        if c2 <= c:
            c2 = c
        return c2
        c = 0
    return c2


In [141]:
mode(arr_4)

1

In [162]:
mode_list(arr_4)

4

In [126]:
arr_4

array([1, 2, 3, 4, 4, 4, 5, 3])

In [143]:
def count(a):
    c = 0
    for i in a:
        c = c+1
    return c

In [144]:
count(arr_4)

8

In [148]:
list_1 = [1,3,4,5,6,4,2,1]

In [149]:
max(list_1)

6

In [163]:
arr_5 = np.random.randint(2,20, size = 25)

In [164]:
arr_5

array([ 5, 13,  7, 11,  7, 10, 19,  6, 11,  4, 16,  9,  5, 14,  9, 13,  8,
        2, 11,  3, 18, 19,  4, 11, 11])

In [166]:
mode_list(arr_5)

11

In [201]:
arr_6 = np.array([1,1,1,1,1,2,2,2,2,2,3,4,5,6])

In [225]:
list_6 = arr_6.tolist()
print (list_6)
set_6 = set(list_6)
print (set_6)
new_list = []
for z in set_6:
    new_list.append(z)
print(new_list)
#list_6_new = list(set_6)
#print(list_6.count(set_6[0]))

[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 4, 5, 6]
{1, 2, 3, 4, 5, 6}
[1, 2, 3, 4, 5, 6]


In [202]:
mode_list(arr_6)

1
10
(1, 10)
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1]


In [226]:
lit = [5,5,1,2,4]

In [227]:
lit.index(5)

0

In [196]:
def mode_list(a):
    c = 0
    list = []
    master_list = []
    for i in a:
         
            for j in a:
                if i == j:
                    c = c+1
            list.append(c)
            c = 0
        
        
    #return list
    
    max_repition = max(list)
    main_index = list.index(max_repition)
    print (a[main_index])
    print (list.count(max(list)))
    Tuple = (a[main_index],list.count(max(list)))
    print (Tuple)
    print (list)

In [197]:
mode_list(arr_6)

1
10
(1, 10)
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1]


In [193]:
arr_6 = np.array([1, 1, 1, 1,1, 2, 2, 2, 2, 2, 3, 4, 5, 6])

In [182]:
list_e.count(5)

5

In [194]:
def mode_list(a):
    c = 0
    list = []
    master_list = []
    master = 0
    while master < len(a):
        for i in a:

                for j in a:
                    if i == j:
                        c = c+1
                list.append(c)
                c = 0


        #return list

        max_repition = max(list)
        main_index = list.index(max_repition)
        
        master = master +1
    print (a[main_index])
    print (list.count(max(list)))
    Tuple = (a[main_index],list.count(max(list)))
    print (Tuple)
    master_list.append(Tuple)
    print (master_list)
    print (list)

In [228]:
mode_list(arr_6)

1
10
(1, 10)
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1]


In [260]:
def mode(a):
    list_count = []
    
    list_ia = [] #converting the input array into a list
    for y in a:
        list_ia.append(y)
    
    set_a = set(a) # We got unique elements of input array in list_a in this block
    list_a = []
    for i in set_a:
        list_a.append(i)
    
    for j in list_a: #We got the list of count in this block
        c = list_ia.count(j)
        list_count.append(c)
        
    maximum_count = max(list_count)
    l = 0
    list_index = []
    while l < len(list_count): # We are finding the indices of the highest count
        if list_count[l] == maximum_count:
            list_index.append(l)
        l = l+1
    
    #master_list = []
    for t in list_index:
        print(list_a[t],'is', list_count[t], 'times')
    
    
    #print(list_a)
    #print(list_count)
    #print(list_index)
    
        

In [261]:
arr_6

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 4, 5, 6])

In [262]:
mode(arr_6)

1 is 5 times
2 is 5 times


In [263]:
arr_7 = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3,3,3,3,3, 4, 5, 6])

In [264]:
mode(arr_7)

1 is 5 times
2 is 5 times
3 is 5 times


In [265]:
#calculation of variance

In [266]:
arr_8 = np.random.randint(10, 20, size = 20)

In [267]:
arr_8

array([12, 15, 15, 11, 14, 17, 18, 17, 18, 19, 11, 11, 10, 14, 14, 10, 13,
       11, 10, 11])

In [286]:
def variance(a):
    
    count = 0
    for i in a:
        count = count + 1
    
    mean_a = mean(a)
    
    list_new = []
    t = 0
    for i in a:
        t = t + (i - mean_a)**2
    variance = t/(count-1)
    standard_dev = variance ** 0.5
    
    print("variance is", variance, 'and std_dev is', standard_dev )
    #rint(standard_dev)
        
    

In [287]:
variance(arr_8)

variance is 8.99736842105 and std_dev is 2.99956137144


In [288]:
list_yy = [1,34,2,34,2,12,3,89,56,6,5]

In [293]:
arr_yy = np.array(list_yy)

In [294]:
arr_yy

array([ 1,  2,  2,  3,  5,  6, 12, 34, 34, 56, 89])

In [308]:
arr_yy = np.random.randint(10, 20, size = 20)

In [309]:
arr_yy

array([15, 13, 16, 15, 14, 18, 16, 18, 17, 10, 13, 11, 12, 15, 17, 11, 16,
       17, 18, 13])

In [310]:
l = []
for i in arr_yy:
    l.append(i)
    
print(l)

[15, 13, 16, 15, 14, 18, 16, 18, 17, 10, 13, 11, 12, 15, 17, 11, 16, 17, 18, 13]


In [302]:
arr_yy_2 = np.array(l)
type(arr_yy_2)

numpy.ndarray

In [306]:
arr_yy_2 = np.array(l.sort())
print(arr_yy_2)

None


In [315]:
l = l.sort()
print (l)

None


In [314]:
l

[10,
 11,
 11,
 12,
 13,
 13,
 13,
 14,
 15,
 15,
 15,
 16,
 16,
 16,
 17,
 17,
 17,
 18,
 18,
 18]